name: SonarCloud Scan

on:
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=PhuHuynh197_ProjectSCGH2 \
            -Dsonar.organization=phuhuynh197 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Generate Markdown Report (Trivy + Snyk + Sonar)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x generate-security-report.sh
          ./generate-security-report.sh

      - name: Upload security-report.md
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.md

      - name: Commit security report
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/PhuHuynh197/Security-Report.git dest-repo
          cp security-report.md dest-repo/
          cd dest-repo
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -f security-report.md
          git commit -m "Add latest security scan report"
          git push origin main
